{
 "title": "GoBin Example",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  { "title": "Histogram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Histogram durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(metricsdemo_demobin_basichistogram_sum[5m]) * 1000",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Histogram bucket counts over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(metricsdemo_demobin_basichistogram_count[5m])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Latest Histogram bucket counts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metricsdemo_demobin_basichistogram_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram bucket counts over time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(metricsdemo_demobin_basichistogram_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Histogram quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(metricsdemo_demobin_basichistogram_bucket[5m])) by (le))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(metricsdemo_demobin_basichistogram_bucket[5m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(metricsdemo_demobin_basichistogram_bucket[5m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gauge history",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "expr": "metricsdemo_demobin_basicgauge" }
     ]
    },
    {
     "title": "Gauge history",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "metricsdemo_demobin_basicgauge" }
     ]
    },
    {
     "title": "*_over_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "min_over_time(metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "min_over_time"
      },
      {
       "expr": "max_over_time(metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "max_over_time"
      },
      {
       "expr": "avg_over_time(metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "avg_over_time"
      },
      {
       "expr": "stddev_over_time(metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "stddev_over_time"
      },
      {
       "expr": "stdvar_over_time(metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "stdvar_over_time"
      },
      {
       "expr": "quantile_over_time(0.9, metricsdemo_demobin_basicgauge[1m])",
       "legendFormat": "quantile_over_time(0.9)"
      }
     ]
    }
   ]
  },
  {
   "title": "Counter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Counter",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "metricsdemo_demobin_basiccounter"
      }
     ]
    },
    {
     "title": "rate(Counter[1m])",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "rate(metricsdemo_demobin_basiccounter[1m])"
      }
     ]
    }
   ]
  }
 ]
}