{
 "title": "Prometheus Example",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "duration rate [1/s]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rpc_durations_histogram_seconds_bucket[30s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "duration rate [1/s]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rpc_durations_histogram_seconds_bucket[30s]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "counts of duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(rpc_durations_seconds_count[5m])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "avg(durations)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(rpc_durations_seconds_sum[5m])/\nrate(rpc_durations_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(rpc_durations_seconds_sum[5m])"
    }
   ]
  }
 ]
}