version: "2.3"

services:
  prometheus:
    image: prom/prometheus:v2.29.1
    container_name: grafana_demo_prometheus
    volumes:
      - ${DEPLOY_FOLDER}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana_demo_grafana
    volumes:
      - ${DEPLOY_FOLDER}/grafana/:/etc/grafana/provisioning/:ro
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - "prometheus"

networks: 
  default: 
    external: 
      name: grafana-demo

